baseURL = 'https://jinqiudr.github.io/'
languageCode = 'zh-cn'
title = "jinqiudr's Blog"
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    author = "jinqiudr"
    disableSpecial1stPost = true

[markup]
  [markup.highlight]
    noClasses = false          # 关键：必须为 false，以便通过 CSS 切换深浅色
    lineNos = true             # 开启行号
    lineNumbersInTable = true  # 强烈推荐：使用表格布局，复制代码时不会选到行号